remote_theme: pages-themes/hacker@v0.2.0
title: OpenBSD Notes
description: My collection of OpenBSD notes and documentation
baseurl: "/openbsdnotes"
url: "https://ignacio2600.github.io"

plugins:
  - jekyll-remote-theme
