title: OpenBSD Notes
description: My collection of OpenBSD notes and documentation
remote_theme: pages-themes/hacker@v0.2.0

url: "https://ignacio2600.github.io"
baseurl: "/openbsdnotes"   # important for project pages
